# Generated by Django 5.2.7 on 2026-01-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0002_job_category_job_status_companyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, help_text='Raw text extracted from PDF/DOCX')),
                ('cleaned_text', models.TextField(blank=True, help_text='Cleaned and normalized text for NLP')),
                ('sections_json', models.JSONField(default=dict, help_text='Detected sections: {skills, experience, education, projects, ...}')),
                ('embedding', models.BinaryField(blank=True, help_text='Semantic embedding vector (384 dims, stored as binary)', null=True)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resume', to='ann.candidateprofile')),
            ],
            options={
                'verbose_name': 'Parsed Resume',
                'verbose_name_plural': 'Parsed Resumes',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(help_text="Original skill text: 'Machine Learning'", max_length=200)),
                ('normalized_text', models.CharField(help_text="Lowercase normalized: 'machine learning'", max_length=200)),
                ('proficiency_level', models.IntegerField(default=3, help_text='1=Beginner, 2=Basic, 3=Intermediate, 4=Proficient, 5=Expert')),
                ('source', models.CharField(choices=[('skills_section', 'Skills Section'), ('experience', 'Experience Section'), ('projects', 'Projects Section'), ('education', 'Education Section'), ('summary', 'Summary/Objective'), ('full_text', 'Full Text Analysis')], default='full_text', max_length=50)),
                ('context', models.TextField(blank=True, help_text='Sentence where skill was found (for explainability)')),
                ('confidence_score', models.FloatField(default=0.8, help_text='NLP extraction confidence (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='ann.candidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Skill',
                'verbose_name_plural': 'Candidate Skills',
                'indexes': [models.Index(fields=['normalized_text'], name='ann_candida_normali_d16099_idx'), models.Index(fields=['candidate', 'proficiency_level'], name='ann_candida_candida_fa8a47_idx')],
                'unique_together': {('candidate', 'normalized_text')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(help_text='Original skill text from job description', max_length=200)),
                ('normalized_text', models.CharField(help_text='Lowercase normalized for matching', max_length=200)),
                ('importance', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('nice_to_have', 'Nice to Have')], default='required', help_text='Skill importance for weighted scoring', max_length=20)),
                ('context', models.TextField(blank=True, help_text='Context where skill was mentioned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='ann.job')),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'indexes': [models.Index(fields=['normalized_text'], name='ann_jobskil_normali_2a8a81_idx'), models.Index(fields=['job', 'importance'], name='ann_jobskil_job_id_b00e89_idx')],
                'unique_together': {('job', 'normalized_text')},
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='Final match score 0-100%')),
                ('semantic_similarity', models.FloatField(default=0, help_text='Text similarity via embeddings (0-100)')),
                ('skill_match_score', models.FloatField(default=0, help_text='Skill overlap score (0-100)')),
                ('experience_match_score', models.FloatField(default=0, help_text='Experience fit score (0-100)')),
                ('education_match_score', models.FloatField(default=0, help_text='Education relevance score (0-100)')),
                ('profile_completeness_score', models.FloatField(default=0, help_text='Profile completeness (0-100)')),
                ('matched_skills', models.JSONField(default=list, help_text='Skills that matched: [{skill, matched_with, importance}]')),
                ('missing_skills', models.JSONField(default=list, help_text='Skills candidate lacks: [{skill, importance}]')),
                ('suggestions', models.JSONField(default=list, help_text="Improvement tips: ['Add Docker to improve by 5%']")),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True, help_text='False if resume or job was updated since calculation')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='ann.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='ann.job')),
            ],
            options={
                'verbose_name': 'Match Score',
                'verbose_name_plural': 'Match Scores',
                'ordering': ['-overall_score'],
                'indexes': [models.Index(fields=['candidate', 'overall_score'], name='ann_matchsc_candida_ef5bcb_idx'), models.Index(fields=['job', 'overall_score'], name='ann_matchsc_job_id_fc6ebe_idx'), models.Index(fields=['is_valid'], name='ann_matchsc_is_vali_6482f1_idx')],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
