# Generated by Django 5.2.7 on 2026-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0003_phase1_ai_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateskill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('domain', 'Domain'), ('soft', 'Soft')], default='domain', help_text='Skill category for weighted scoring', max_length=20),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('domain', 'Domain'), ('soft', 'Soft')], default='domain', help_text='Skill category for weighted scoring', max_length=20),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['category'], name='ann_candida_categor_4085c9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['category'], name='ann_jobskil_categor_d64c22_idx'),
        ),
    ]
