# Generated by Django 5.2.7 on 2026-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0004_phase3_skill_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='education_field',
            field=models.CharField(blank=True, help_text='Field of study (e.g., Computer Science, Law)', max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('other', 'Other')], help_text='Highest education level', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Semantic embedding vector (384 dims, stored as binary)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_max',
            field=models.IntegerField(default=99, help_text='Maximum years of experience (99 = no limit)'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_min',
            field=models.IntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
